mixed-port: 7890
ipv6: false
allow-lan: true
mode: rule
log-level: warning
unified-delay: false
tcp-concurrent: true
geo-auto-update: true
geo-update-interval: 168
external-controller: 127.0.0.1:9090
external-controller-cors:
  allow-origins:
  - '*'
  allow-private-network: true
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  respect-rules: true
  use-system-hosts: false
  listen: 0.0.0.0:1053
  ipv6: false
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  proxy-server-nameserver:
  - 8.8.8.8
  direct-nameserver:
  - 8.8.8.8
  direct-nameserver-follow-policy: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.localhost'
  - '*.ir'
  - '*.test'
  - '*.localdomain'
  - '*.home'
  - '*.internal'
tun:
  enable: true
  stack: gvisor
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
proxies:
- name: 'ARISTA🔥 #1'
  type: ss
  server: series-a1.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: W74XFALLLuw6m5IA
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #2'
  type: ss
  server: 94.131.123.86
  port: 35361
  cipher: chacha20-ietf-poly1305
  password: SSmfl4Tq1rRlB7boDY3jlt
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #3'
  type: ss
  server: 154.205.145.37
  port: 11201
  cipher: chacha20-ietf-poly1305
  password: 47509ba3679b9df9
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #4'
  type: ss
  server: 62.133.63.167
  port: 61377
  cipher: chacha20-ietf-poly1305
  password: E12yZBPC7y8SnmkSYjf0Wl
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #5'
  type: ss
  server: 192.248.148.230
  port: 1080
  cipher: aes-128-gcm
  password: FgEOE37QjVfd72coc4kuEA
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #6'
  type: ss
  server: admin.c2.havij.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: kaQH3hGdcP80XEDI
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #7'
  type: ss
  server: admin.c1.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: W74XFALLLuw6m5IA
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #8'
  type: ss
  server: series-a2.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: W74XFALLLuw6m5IA
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #9'
  type: ss
  server: bestout2.curtvjix.ir
  port: 9723
  cipher: chacha20-ietf-poly1305
  password: 6/dQH36JXyvoJPYU3k+hY5jZjEow9uZxposQZK4cNy4=
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #10'
  type: ss
  server: 64.176.215.70
  port: 80
  cipher: aes-256-gcm
  password: hbhO0xomsJzhO24F
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #11'
  type: ss
  server: 51.75.168.50
  port: 13030
  cipher: chacha20-ietf-poly1305
  password: 6c815bb84c781da5
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #14'
  type: ss
  server: 82.38.31.184
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: k1dBOmOB4oqi7Ump37a1bQ
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #15'
  type: ss
  server: 94.72.127.55
  port: 80
  cipher: aes-256-gcm
  password: wlJSF0fC8uqB5Gm5
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #16'
  type: ss
  server: 45.95.233.133
  port: 8388
  cipher: chacha20-ietf-poly1305
  password: KEN_L6msL8rmuSPywR4M0qM_1_txZ8D5
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #17'
  type: ss
  server: 103.106.228.175
  port: 8009
  cipher: aes-256-gcm
  password: XKFKl2rULjIp74
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #18'
  type: ss
  server: 193.29.139.199
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: QCXDxuDlTTMD7jtgHUjIoj
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #19'
  type: ss
  server: 194.233.94.119
  port: 80
  cipher: aes-256-gcm
  password: 8t2xeemUtyui4zAv
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #20'
  type: ss
  server: 212.57.115.240
  port: 33386
  cipher: chacha20-ietf-poly1305
  password: 12qBKfsbd0RjO0vqEhgsaccwp
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #21'
  type: ss
  server: 193.29.139.162
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: cvII85TrW6n0OGyfpHVS1u
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #22'
  type: ss
  server: 45.80.231.75
  port: 31019
  cipher: chacha20-ietf-poly1305
  password: XN6Xf0ZqwDeFrt39TQraen
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #23'
  type: ss
  server: 154.17.31.189
  port: 18829
  cipher: aes-128-gcm
  password: fa593414-7a76-4975-909b-7a7c46be123b
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #24'
  type: ss
  server: 149.102.149.207
  port: 443
  cipher: aes-256-gcm
  password: umWwoQJEJGf74SLe
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #25'
  type: ss
  server: 213.156.137.142
  port: 43661
  cipher: chacha20-ietf-poly1305
  password: cc27a3012d81a44c
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #26'
  type: ss
  server: 82.38.31.103
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: oZIoA69Q8yhcQV8ka3Pa3A
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #27'
  type: ss
  server: 57.129.95.198
  port: 11201
  cipher: chacha20-ietf-poly1305
  password: d6b0973401858b29
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #28'
  type: ss
  server: 193.29.139.141
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: oZIoA69Q8yhcQV8ka3Pa3A
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #29'
  type: ss
  server: 138.124.118.94
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: ujS5f_Tew132Vzw2x0j-uvv6R7f_Hq3V
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #30'
  type: ss
  server: 103.186.155.29
  port: 38388
  cipher: aes-256-cfb
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #31'
  type: ss
  server: 103.186.155.154
  port: 38388
  cipher: aes-256-cfb
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #32'
  type: ss
  server: 103.186.154.152
  port: 38388
  cipher: aes-256-cfb
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  udp: true
  tcp-fast-open: true
proxy-groups:
- name: Proxy Select
  type: select
  proxies:
  - Auto Select
  - 'ARISTA🔥 #1'
  - 'ARISTA🔥 #2'
  - 'ARISTA🔥 #3'
  - 'ARISTA🔥 #4'
  - 'ARISTA🔥 #5'
  - 'ARISTA🔥 #6'
  - 'ARISTA🔥 #7'
  - 'ARISTA🔥 #8'
  - 'ARISTA🔥 #9'
  - 'ARISTA🔥 #10'
  - 'ARISTA🔥 #11'
  - 'ARISTA🔥 #14'
  - 'ARISTA🔥 #15'
  - 'ARISTA🔥 #16'
  - 'ARISTA🔥 #17'
  - 'ARISTA🔥 #18'
  - 'ARISTA🔥 #19'
  - 'ARISTA🔥 #20'
  - 'ARISTA🔥 #21'
  - 'ARISTA🔥 #22'
  - 'ARISTA🔥 #23'
  - 'ARISTA🔥 #24'
  - 'ARISTA🔥 #25'
  - 'ARISTA🔥 #26'
  - 'ARISTA🔥 #27'
  - 'ARISTA🔥 #28'
  - 'ARISTA🔥 #29'
  - 'ARISTA🔥 #30'
  - 'ARISTA🔥 #31'
  - 'ARISTA🔥 #32'
  - DIRECT
- name: Auto Select
  type: url-test
  proxies:
  - 'ARISTA🔥 #1'
  - 'ARISTA🔥 #2'
  - 'ARISTA🔥 #3'
  - 'ARISTA🔥 #4'
  - 'ARISTA🔥 #5'
  - 'ARISTA🔥 #6'
  - 'ARISTA🔥 #7'
  - 'ARISTA🔥 #8'
  - 'ARISTA🔥 #9'
  - 'ARISTA🔥 #10'
  - 'ARISTA🔥 #11'
  - 'ARISTA🔥 #14'
  - 'ARISTA🔥 #15'
  - 'ARISTA🔥 #16'
  - 'ARISTA🔥 #17'
  - 'ARISTA🔥 #18'
  - 'ARISTA🔥 #19'
  - 'ARISTA🔥 #20'
  - 'ARISTA🔥 #21'
  - 'ARISTA🔥 #22'
  - 'ARISTA🔥 #23'
  - 'ARISTA🔥 #24'
  - 'ARISTA🔥 #25'
  - 'ARISTA🔥 #26'
  - 'ARISTA🔥 #27'
  - 'ARISTA🔥 #28'
  - 'ARISTA🔥 #29'
  - 'ARISTA🔥 #30'
  - 'ARISTA🔥 #31'
  - 'ARISTA🔥 #32'
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 150
  lazy: true
rules:
- DOMAIN-SUFFIX,net2025.afsharidempire.uk,DIRECT
- DOMAIN,cp.cloudflare.com,Auto Select
- DOMAIN-SUFFIX,cdn.ir,DIRECT
- DOMAIN-SUFFIX,aparat.com,DIRECT
- DOMAIN-SUFFIX,digikala.com,DIRECT
- DOMAIN-SUFFIX,divar.ir,DIRECT
- DOMAIN-SUFFIX,snapp.ir,DIRECT
- DOMAIN-SUFFIX,torob.com,DIRECT
- DOMAIN-SUFFIX,bamilo.com,DIRECT
- DOMAIN-SUFFIX,alibaba.ir,DIRECT
- DOMAIN-SUFFIX,ban.ir,DIRECT
- DOMAIN-KEYWORD,telegram,Auto Select
- DOMAIN-SUFFIX,t.me,Auto Select
- DOMAIN-SUFFIX,telegram.org,Auto Select
- DOMAIN-SUFFIX,google.com,Auto Select
- DOMAIN-SUFFIX,youtube.com,Auto Select
- DOMAIN-SUFFIX,github.com,Auto Select
- DOMAIN-SUFFIX,instagram.com,Auto Select
- DOMAIN-SUFFIX,twitter.com,Auto Select
- DOMAIN-SUFFIX,whatsapp.com,Auto Select
- GEOIP,IR,DIRECT
- MATCH,Proxy Select
ntp:
  enable: true
  server: time.cloudflare.com
  port: 123
  interval: 30
