mixed-port: 7890
ipv6: false
allow-lan: true
mode: rule
log-level: warning
unified-delay: false
tcp-concurrent: true
geo-auto-update: true
geo-update-interval: 168
external-controller: 127.0.0.1:9090
external-controller-cors:
  allow-origins:
  - '*'
  allow-private-network: true
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  respect-rules: true
  use-system-hosts: false
  listen: 0.0.0.0:1053
  ipv6: false
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  proxy-server-nameserver:
  - 8.8.8.8
  direct-nameserver:
  - 8.8.8.8
  direct-nameserver-follow-policy: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.localhost'
  - '*.ir'
  - '*.test'
  - '*.localdomain'
  - '*.home'
  - '*.internal'
tun:
  enable: true
  stack: gvisor
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
proxies:
- name: 'ARISTA🔥 #1'
  type: ss
  server: 185.123.101.64
  port: 2376
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #2'
  type: ss
  server: 193.29.139.202
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: oZIoA69Q8yhcQV8ka3Pa3A
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #3'
  type: ss
  server: 193.29.139.206
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: 4a2rfixophdjffa8KVA4Aa
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #4'
  type: ss
  server: 154.53.60.212
  port: 80
  cipher: aes-256-gcm
  password: ZfbPFDdeBj0B1Txs
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #5'
  type: ss
  server: 195.93.253.240
  port: 14130
  cipher: chacha20-ietf-poly1305
  password: Y66N7eDMqbn5uPWEu5Vpy1
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #6'
  type: ss
  server: 144.126.158.195
  port: 12053
  cipher: chacha20-ietf-poly1305
  password: b537ba3e4f4cda0c
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #7'
  type: ss
  server: 45.136.31.53
  port: 7013
  cipher: aes-256-gcm
  password: f36520aa-a3dc-4144-bef9-cfd4a310f2f3
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #8'
  type: ss
  server: 62.146.171.59
  port: 80
  cipher: aes-256-gcm
  password: MEmsQeJtPF1GMwJm
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #9'
  type: ss
  server: 107.172.20.55
  port: 7002
  cipher: aes-256-gcm
  password: 65025369-720b-4792-9f7e-163b0372a4ad
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #10'
  type: ss
  server: 163.171.148.71
  port: 11201
  cipher: chacha20-ietf-poly1305
  password: 312ee9bcc9570095
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #11'
  type: ss
  server: 158.173.20.171
  port: 443
  cipher: aes-128-gcm
  password: shadowsocks
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #12'
  type: ss
  server: 158.173.20.171
  port: 443
  cipher: aes-128-gcm
  password: shadowsocks
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #13'
  type: ss
  server: 114.35.191.75
  port: 50099
  cipher: chacha20-ietf-poly1305
  password: 7e731ec3-f8e1-43f6-92cf-3978d14705c4
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #14'
  type: ss
  server: tinkered-pennies-puppies.freesocks.work
  port: 443
  cipher: chacha20-ietf-poly1305
  password: hbGrpfvNrJsUmKmPbR3iY2
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #15'
  type: ss
  server: 151.242.251.144
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: 4a2rfixophdjffa8KVA4Aa
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #16'
  type: ss
  server: 54.37.78.130
  port: 11201
  cipher: chacha20-ietf-poly1305
  password: d954bd6dd74a7f48
  udp: true
  tcp-fast-open: true
proxy-groups:
- name: Proxy Select
  type: select
  proxies:
  - Auto Select
  - 'ARISTA🔥 #1'
  - 'ARISTA🔥 #2'
  - 'ARISTA🔥 #3'
  - 'ARISTA🔥 #4'
  - 'ARISTA🔥 #5'
  - 'ARISTA🔥 #6'
  - 'ARISTA🔥 #7'
  - 'ARISTA🔥 #8'
  - 'ARISTA🔥 #9'
  - 'ARISTA🔥 #10'
  - 'ARISTA🔥 #11'
  - 'ARISTA🔥 #12'
  - 'ARISTA🔥 #13'
  - 'ARISTA🔥 #14'
  - 'ARISTA🔥 #15'
  - 'ARISTA🔥 #16'
  - DIRECT
- name: Auto Select
  type: url-test
  proxies:
  - 'ARISTA🔥 #1'
  - 'ARISTA🔥 #2'
  - 'ARISTA🔥 #3'
  - 'ARISTA🔥 #4'
  - 'ARISTA🔥 #5'
  - 'ARISTA🔥 #6'
  - 'ARISTA🔥 #7'
  - 'ARISTA🔥 #8'
  - 'ARISTA🔥 #9'
  - 'ARISTA🔥 #10'
  - 'ARISTA🔥 #11'
  - 'ARISTA🔥 #12'
  - 'ARISTA🔥 #13'
  - 'ARISTA🔥 #14'
  - 'ARISTA🔥 #15'
  - 'ARISTA🔥 #16'
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 150
  lazy: true
rules:
- DOMAIN-SUFFIX,net2025.afsharidempire.uk,DIRECT
- DOMAIN,cp.cloudflare.com,Auto Select
- DOMAIN-SUFFIX,cdn.ir,DIRECT
- DOMAIN-SUFFIX,aparat.com,DIRECT
- DOMAIN-SUFFIX,digikala.com,DIRECT
- DOMAIN-SUFFIX,divar.ir,DIRECT
- DOMAIN-SUFFIX,snapp.ir,DIRECT
- DOMAIN-SUFFIX,torob.com,DIRECT
- DOMAIN-SUFFIX,bamilo.com,DIRECT
- DOMAIN-SUFFIX,alibaba.ir,DIRECT
- DOMAIN-SUFFIX,ban.ir,DIRECT
- DOMAIN-KEYWORD,telegram,Auto Select
- DOMAIN-SUFFIX,t.me,Auto Select
- DOMAIN-SUFFIX,telegram.org,Auto Select
- DOMAIN-SUFFIX,google.com,Auto Select
- DOMAIN-SUFFIX,youtube.com,Auto Select
- DOMAIN-SUFFIX,github.com,Auto Select
- DOMAIN-SUFFIX,instagram.com,Auto Select
- DOMAIN-SUFFIX,twitter.com,Auto Select
- DOMAIN-SUFFIX,whatsapp.com,Auto Select
- GEOIP,IR,DIRECT
- MATCH,Proxy Select
ntp:
  enable: true
  server: time.cloudflare.com
  port: 123
  interval: 30
