mixed-port: 7890
ipv6: false
allow-lan: true
mode: rule
log-level: warning
unified-delay: false
tcp-concurrent: true
geo-auto-update: true
geo-update-interval: 168
external-controller: 127.0.0.1:9090
external-controller-cors:
  allow-origins:
  - '*'
  allow-private-network: true
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  respect-rules: true
  use-system-hosts: false
  listen: 0.0.0.0:1053
  ipv6: false
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  proxy-server-nameserver:
  - 8.8.8.8
  direct-nameserver:
  - 8.8.8.8
  direct-nameserver-follow-policy: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.localhost'
  - '*.ir'
  - '*.test'
  - '*.localdomain'
  - '*.home'
  - '*.internal'
tun:
  enable: true
  stack: gvisor
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
proxies:
- name: 'ARISTA🔥 #1'
  type: ss
  server: 91.107.144.0
  port: 1080
  cipher: chacha20-ietf-poly1305
  password: kDt8cG1TLg4uB0nUMOAu
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #2'
  type: ss
  server: 91.107.144.0
  port: 1080
  cipher: chacha20-ietf-poly1305
  password: kDt8cG1TLg4uB0nUMOAu
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #3'
  type: ss
  server: 103.186.155.105
  port: 38388
  cipher: aes-256-cfb
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #4'
  type: ss
  server: download.riferoser.icu
  port: 56594
  cipher: chacha20-ietf-poly1305
  password: 2zQoJHz22Zbvh37yxZWJ6JzFtLhttZCLop8WFfpcJ4166JAenuKTvDuUnebBnz8PGPoXLWsEm1nkzbTnJaiTsSx9wXZkyL3i
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #5'
  type: ss
  server: 163.171.181.49
  port: 42935
  cipher: chacha20-ietf-poly1305
  password: 877c3b069c335ffc
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #6'
  type: ss
  server: 154.38.176.7
  port: 80
  cipher: aes-256-gcm
  password: nKeE2ZFWVaE4DyjR
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #8'
  type: ss
  server: 138.124.118.94
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: c5LWfhsktozSmxNzUPjnM0NwZyNeMM2d
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #9'
  type: ss
  server: 216.105.168.18
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1GliChaixFQXOmAV3IENP3
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #10'
  type: ss
  server: 141.98.101.179
  port: 443
  cipher: aes-128-gcm
  password: shadowsocks
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #11'
  type: ss
  server: 203.202.232.78
  port: 60299
  cipher: chacha20-ietf-poly1305
  password: AVLbEUEtBD59FsRqcNyEib
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #12'
  type: ss
  server: 209.74.82.156
  port: 18571
  cipher: chacha20-ietf-poly1305
  password: PYEU2YIb0XkFGakKZ04OnP
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #13'
  type: ss
  server: 193.29.139.141
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: oZIoA69Q8yhcQV8ka3Pa3A
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #14'
  type: ss
  server: 112.197.26.106
  port: 45312
  cipher: chacha20-ietf-poly1305
  password: ca5a5efae00a832b
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #15'
  type: ss
  server: 213.202.208.199
  port: 7001
  cipher: aes-256-gcm
  password: RexnBgU7EV5ADxG
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #16'
  type: ss
  server: 141.98.101.181
  port: 443
  cipher: aes-128-gcm
  password: shadowsocks
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #17'
  type: ss
  server: 212.57.115.240
  port: 33386
  cipher: chacha20-ietf-poly1305
  password: 12qBKfsbd0RjO0vqEhgsaccwp
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #18'
  type: ss
  server: 195.58.49.100
  port: 60129
  cipher: aes-256-gcm
  password: 9f3d1a6d31468599
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #19'
  type: ss
  server: 141.98.101.182
  port: 443
  cipher: aes-128-gcm
  password: shadowsocks
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #20'
  type: ss
  server: 82.38.31.103
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: oZIoA69Q8yhcQV8ka3Pa3A
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #21'
  type: ss
  server: 71.19.148.143
  port: 443
  cipher: chacha20-ietf-poly1305
  password: p78naCf2EfOlRSLTX0wFVx
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #22'
  type: ss
  server: 103.186.154.68
  port: 38388
  cipher: aes-256-cfb
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #23'
  type: ss
  server: 217.30.10.18
  port: 9084
  cipher: aes-256-cfb
  password: c3NtHJ5ujV2tGDfj
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #24'
  type: ss
  server: 45.87.175.165
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: QCXDxuDlTTMD7jtgHUjIoj
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #25'
  type: ss
  server: 103.186.155.147
  port: 38388
  cipher: aes-256-cfb
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #26'
  type: ss
  server: 103.163.218.2
  port: 989
  cipher: aes-256-cfb
  password: f8f7aCzcPKbsF8p3
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #27'
  type: ss
  server: 45.144.31.24
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 7HQ8w1YWMdNjq68bZt1tNfpDHLFA1BPA
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #28'
  type: ss
  server: 45.87.175.65
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: oZIoA69Q8yhcQV8ka3Pa3A
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #29'
  type: ss
  server: 103.186.155.60
  port: 38388
  cipher: aes-256-cfb
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #30'
  type: ss
  server: 176.126.83.158
  port: 990
  cipher: chacha20-ietf-poly1305
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #31'
  type: ss
  server: 163.171.181.49
  port: 48852
  cipher: chacha20-ietf-poly1305
  password: abc484edcf1be43c
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #32'
  type: ss
  server: 57.129.95.38
  port: 11201
  cipher: chacha20-ietf-poly1305
  password: f54cdee10f8b25ce
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #33'
  type: ss
  server: 38.180.197.41
  port: 8080
  cipher: aes-256-gcm
  password: KixLvKzwjekG00rm
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #34'
  type: ss
  server: 5.181.2.76
  port: 36608
  cipher: chacha20-ietf-poly1305
  password: JOZ5Mb3nJCmmoKhd8Cc9aC
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #35'
  type: ss
  server: 51.159.103.137
  port: 18290
  cipher: aes-128-gcm
  password: mBl1fYhX88xk3K39IePrRnmsQDvb1h4f
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #36'
  type: ss
  server: 154.46.31.106
  port: 443
  cipher: chacha20-ietf-poly1305
  password: QFWzCw2uX9B9i6qAYeFBIE
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #37'
  type: ss
  server: 95.173.218.203
  port: 990
  cipher: chacha20-ietf-poly1305
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #38'
  type: ss
  server: 57.129.140.88
  port: 8388
  cipher: chacha20-ietf-poly1305
  password: k1v5g9FefdoO
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #39'
  type: ss
  server: 82.38.31.202
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: k1dBOmOB4oqi7Ump37a1bQ
  udp: true
  tcp-fast-open: true
proxy-groups:
- name: Proxy Select
  type: select
  proxies:
  - Auto Select
  - 'ARISTA🔥 #1'
  - 'ARISTA🔥 #2'
  - 'ARISTA🔥 #3'
  - 'ARISTA🔥 #4'
  - 'ARISTA🔥 #5'
  - 'ARISTA🔥 #6'
  - 'ARISTA🔥 #8'
  - 'ARISTA🔥 #9'
  - 'ARISTA🔥 #10'
  - 'ARISTA🔥 #11'
  - 'ARISTA🔥 #12'
  - 'ARISTA🔥 #13'
  - 'ARISTA🔥 #14'
  - 'ARISTA🔥 #15'
  - 'ARISTA🔥 #16'
  - 'ARISTA🔥 #17'
  - 'ARISTA🔥 #18'
  - 'ARISTA🔥 #19'
  - 'ARISTA🔥 #20'
  - 'ARISTA🔥 #21'
  - 'ARISTA🔥 #22'
  - 'ARISTA🔥 #23'
  - 'ARISTA🔥 #24'
  - 'ARISTA🔥 #25'
  - 'ARISTA🔥 #26'
  - 'ARISTA🔥 #27'
  - 'ARISTA🔥 #28'
  - 'ARISTA🔥 #29'
  - 'ARISTA🔥 #30'
  - 'ARISTA🔥 #31'
  - 'ARISTA🔥 #32'
  - 'ARISTA🔥 #33'
  - 'ARISTA🔥 #34'
  - 'ARISTA🔥 #35'
  - 'ARISTA🔥 #36'
  - 'ARISTA🔥 #37'
  - 'ARISTA🔥 #38'
  - 'ARISTA🔥 #39'
  - DIRECT
- name: Auto Select
  type: url-test
  proxies:
  - 'ARISTA🔥 #1'
  - 'ARISTA🔥 #2'
  - 'ARISTA🔥 #3'
  - 'ARISTA🔥 #4'
  - 'ARISTA🔥 #5'
  - 'ARISTA🔥 #6'
  - 'ARISTA🔥 #8'
  - 'ARISTA🔥 #9'
  - 'ARISTA🔥 #10'
  - 'ARISTA🔥 #11'
  - 'ARISTA🔥 #12'
  - 'ARISTA🔥 #13'
  - 'ARISTA🔥 #14'
  - 'ARISTA🔥 #15'
  - 'ARISTA🔥 #16'
  - 'ARISTA🔥 #17'
  - 'ARISTA🔥 #18'
  - 'ARISTA🔥 #19'
  - 'ARISTA🔥 #20'
  - 'ARISTA🔥 #21'
  - 'ARISTA🔥 #22'
  - 'ARISTA🔥 #23'
  - 'ARISTA🔥 #24'
  - 'ARISTA🔥 #25'
  - 'ARISTA🔥 #26'
  - 'ARISTA🔥 #27'
  - 'ARISTA🔥 #28'
  - 'ARISTA🔥 #29'
  - 'ARISTA🔥 #30'
  - 'ARISTA🔥 #31'
  - 'ARISTA🔥 #32'
  - 'ARISTA🔥 #33'
  - 'ARISTA🔥 #34'
  - 'ARISTA🔥 #35'
  - 'ARISTA🔥 #36'
  - 'ARISTA🔥 #37'
  - 'ARISTA🔥 #38'
  - 'ARISTA🔥 #39'
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 150
  lazy: true
rules:
- DOMAIN-SUFFIX,net2025.afsharidempire.uk,DIRECT
- DOMAIN,cp.cloudflare.com,Auto Select
- DOMAIN-SUFFIX,cdn.ir,DIRECT
- DOMAIN-SUFFIX,aparat.com,DIRECT
- DOMAIN-SUFFIX,digikala.com,DIRECT
- DOMAIN-SUFFIX,divar.ir,DIRECT
- DOMAIN-SUFFIX,snapp.ir,DIRECT
- DOMAIN-SUFFIX,torob.com,DIRECT
- DOMAIN-SUFFIX,bamilo.com,DIRECT
- DOMAIN-SUFFIX,alibaba.ir,DIRECT
- DOMAIN-SUFFIX,ban.ir,DIRECT
- DOMAIN-KEYWORD,telegram,Auto Select
- DOMAIN-SUFFIX,t.me,Auto Select
- DOMAIN-SUFFIX,telegram.org,Auto Select
- DOMAIN-SUFFIX,google.com,Auto Select
- DOMAIN-SUFFIX,youtube.com,Auto Select
- DOMAIN-SUFFIX,github.com,Auto Select
- DOMAIN-SUFFIX,instagram.com,Auto Select
- DOMAIN-SUFFIX,twitter.com,Auto Select
- DOMAIN-SUFFIX,whatsapp.com,Auto Select
- GEOIP,IR,DIRECT
- MATCH,Proxy Select
ntp:
  enable: true
  server: time.cloudflare.com
  port: 123
  interval: 30
