mixed-port: 7890
ipv6: false
allow-lan: true
mode: rule
log-level: warning
unified-delay: false
tcp-concurrent: true
geo-auto-update: true
geo-update-interval: 168
external-controller: 127.0.0.1:9090
external-controller-cors:
  allow-origins:
  - '*'
  allow-private-network: true
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  respect-rules: true
  use-system-hosts: false
  listen: 0.0.0.0:1053
  ipv6: false
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  proxy-server-nameserver:
  - 8.8.8.8
  direct-nameserver:
  - 8.8.8.8
  direct-nameserver-follow-policy: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.localhost'
  - '*.ir'
  - '*.test'
  - '*.localdomain'
  - '*.home'
  - '*.internal'
tun:
  enable: true
  stack: gvisor
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
proxies:
- name: 'Trojan #1'
  type: trojan
  server: 52.29.35.131
  port: 22222
  password: telegram-id-privatevpns
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: trojan.burgerip.co.uk
  client-fingerprint: chrome
  alpn:
  - http/1.1
- name: 'Trojan #2'
  type: trojan
  server: 104.21.40.34
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.gossipglove.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.gossipglove.com
- name: 'Trojan #3'
  type: trojan
  server: 172.64.152.23
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.gossipglove.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.gossipglove.com
- name: 'Trojan #4'
  type: trojan
  server: 188.114.98.0
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.creationlong.org
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.creationlong.org
- name: 'Trojan #5'
  type: trojan
  server: 172.64.152.23
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.gossipglove.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.gossipglove.com
- name: 'Trojan #6'
  type: trojan
  server: u8.ok8.ccwu.cc
  port: 443
  password: 1338f666-2fcc-4538-bc29-1ebf89624383
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: u8.ok8.ccwu.cc
  client-fingerprint: chrome
  alpn:
  - http/1.1
  ws-opts:
    path: /XCLcnSashhgSVE3HOw1VI85y
    headers:
      Host: u8.ok8.ccwu.cc
- name: 'Trojan #7'
  type: trojan
  server: y.taiwan2029.indevs.in
  port: 443
  password: 1798b14b-aee0-4008-ba9a-2e53877761b4
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: y.taiwan2029.indevs.in
  client-fingerprint: chrome
  ws-opts:
    path: /RXvyoH0kyRosKkycyrxcJWNVFC21
    headers:
      Host: y.taiwan2029.indevs.in
- name: 'Trojan #8'
  type: trojan
  server: dddfghyju.taipei102.indevs.in
  port: 443
  password: 2bfe58f7-da1d-45df-ab43-7c665b20ee29
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: dddfghyju.taipei102.indevs.in
  client-fingerprint: chrome
  alpn:
  - http/1.1
  ws-opts:
    path: /2cO5FH0xUmT9oqnbBhmKb8nOkg
    headers:
      Host: dddfghyju.taipei102.indevs.in
- name: 'Trojan #9'
  type: trojan
  server: 188.116.22.217
  port: 2083
  password: 0zmdDXd0Qt5ff_7Qg67R-Rtq4Tmt4c
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: xo.e0f.cx
  client-fingerprint: chrome
  ws-opts:
    path: /trojan-ws
    headers:
      Host: xo.e0f.cx
- name: 'Trojan #10'
  type: trojan
  server: nnmmkk999.890602.xyz
  port: 443
  password: 2bfded8d-6a7c-4c18-aaa5-fc65b955d50c
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: nnmmkk999.890602.xyz
  client-fingerprint: chrome
  ws-opts:
    path: /7vMsF4VUuJ3dX414bl
    headers:
      Host: nnmmkk999.890602.xyz
- name: 'Trojan #11'
  type: trojan
  server: dddfghyju.taipei102.indevs.in
  port: 443
  password: 2bfe58f7-da1d-45df-ab43-7c665b20ee29
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: dddfghyju.taipei102.indevs.in
  client-fingerprint: chrome
  ws-opts:
    path: /2cO5FH0xUmT9oqnbBhmKb8nOkg
    headers:
      Host: dddfghyju.taipei102.indevs.in
- name: 'Trojan #12'
  type: trojan
  server: 172.67.119.227
  port: 8443
  password: Nova-Proxy
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: aliem.derisvx.workers.dev
  client-fingerprint: chrome
  ws-opts:
    path: /?ed
    headers:
      Host: aliem.derisvx.workers.dev
- name: 'Trojan #13'
  type: trojan
  server: 160.16.68.250
  port: 1281
  password: 262f1d150049457ac1d6e66b020fa980
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.nintendogames.net
  client-fingerprint: chrome
- name: 'Trojan #14'
  type: trojan
  server: srv1.khatibirepair.ir
  port: 443
  password: 842b5f9dd11e458d8613c907c4cc5723
  network: raw
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.gpt123.one
  client-fingerprint: chrome
- name: 'Trojan #15'
  type: trojan
  server: 160.16.68.250
  port: 1281
  password: 262f1d150049457ac1d6e66b020fa980
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.nintendogames.net
  client-fingerprint: chrome
- name: 'Trojan #16'
  type: trojan
  server: srv1.khatibirepair.ir
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.creationlong.org
  client-fingerprint: chrome
  ws-opts:
    path: '%2fassignment'
    headers:
      Host: www.creationlong.org
- name: 'Trojan #17'
  type: trojan
  server: 172.64.152.23
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.creationlong.org
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.creationlong.org
- name: 'Trojan #18'
  type: trojan
  server: 3.75.163.105
  port: 22223
  password: telegram-id-v2rayvpnchannel
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: trojan.burgerip.co.uk
  client-fingerprint: chrome
  alpn:
  - http/1.1
- name: 'Trojan #19'
  type: trojan
  server: 51.45.44.114
  port: 22223
  password: telegram-id-v2rayvpnchannel
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: trojan.burgerip.co.uk
  client-fingerprint: chrome
  alpn:
  - http/1.1
- name: 'Trojan #20'
  type: trojan
  server: 51.44.103.139
  port: 22223
  password: telegram-id-v2rayvpnchannel
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: trojan.burgerip.co.uk
  client-fingerprint: chrome
  alpn:
  - http/1.1
- name: 'Trojan #21'
  type: trojan
  server: 52.29.35.131
  port: 22223
  password: telegram-id-v2rayvpnchannel
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: trojan.burgerip.co.uk
  client-fingerprint: chrome
  alpn:
  - http/1.1
- name: 'Trojan #22'
  type: trojan
  server: 104.21.40.34
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.gossipglove.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.gossipglove.com
- name: 'Trojan #23'
  type: trojan
  server: 104.18.7.147
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.creationlong.org
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  ws-opts:
    path: /assignment
    headers:
      Host: www.creationlong.org
- name: 'Trojan #24'
  type: trojan
  server: 172.64.152.23
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.calmlunch.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.calmlunch.com
- name: 'Trojan #25'
  type: trojan
  server: 16.163.102.116
  port: 52951
  password: BxceQaOe
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 16.163.102.116
  client-fingerprint: chrome
- name: 'Trojan #26'
  type: trojan
  server: 172.64.152.23
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.gossipglove.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.gossipglove.com
- name: 'Trojan #27'
  type: trojan
  server: 172.66.44.230
  port: 8443
  password: 8r%3C%5B9%27l6hAO%238ZQi
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: Koma-YT.PAGeS.Dev
  client-fingerprint: chrome
  ws-opts:
    path: /tro8sFW1S91B6sZrM1
    headers:
      Host: Koma-YT.PAGeS.Dev
- name: 'Trojan #28'
  type: trojan
  server: 51.44.103.139
  port: 22223
  password: telegram-id-directvpn
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: trojan.burgerip.co.uk
  client-fingerprint: chrome
  alpn:
  - http/1.1
proxy-groups:
- name: Proxy Select
  type: select
  proxies:
  - Auto Select
  - 'Trojan #1'
  - 'Trojan #2'
  - 'Trojan #3'
  - 'Trojan #4'
  - 'Trojan #5'
  - 'Trojan #6'
  - 'Trojan #7'
  - 'Trojan #8'
  - 'Trojan #9'
  - 'Trojan #10'
  - 'Trojan #11'
  - 'Trojan #12'
  - 'Trojan #13'
  - 'Trojan #14'
  - 'Trojan #15'
  - 'Trojan #16'
  - 'Trojan #17'
  - 'Trojan #18'
  - 'Trojan #19'
  - 'Trojan #20'
  - 'Trojan #21'
  - 'Trojan #22'
  - 'Trojan #23'
  - 'Trojan #24'
  - 'Trojan #25'
  - 'Trojan #26'
  - 'Trojan #27'
  - 'Trojan #28'
  - DIRECT
- name: Auto Select
  type: url-test
  proxies:
  - 'Trojan #1'
  - 'Trojan #2'
  - 'Trojan #3'
  - 'Trojan #4'
  - 'Trojan #5'
  - 'Trojan #6'
  - 'Trojan #7'
  - 'Trojan #8'
  - 'Trojan #9'
  - 'Trojan #10'
  - 'Trojan #11'
  - 'Trojan #12'
  - 'Trojan #13'
  - 'Trojan #14'
  - 'Trojan #15'
  - 'Trojan #16'
  - 'Trojan #17'
  - 'Trojan #18'
  - 'Trojan #19'
  - 'Trojan #20'
  - 'Trojan #21'
  - 'Trojan #22'
  - 'Trojan #23'
  - 'Trojan #24'
  - 'Trojan #25'
  - 'Trojan #26'
  - 'Trojan #27'
  - 'Trojan #28'
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 150
  lazy: true
rules:
- DOMAIN-SUFFIX,net2025.afsharidempire.uk,DIRECT
- DOMAIN,cp.cloudflare.com,Auto Select
- DOMAIN-SUFFIX,cdn.ir,DIRECT
- DOMAIN-SUFFIX,aparat.com,DIRECT
- DOMAIN-SUFFIX,digikala.com,DIRECT
- DOMAIN-SUFFIX,divar.ir,DIRECT
- DOMAIN-SUFFIX,snapp.ir,DIRECT
- DOMAIN-SUFFIX,torob.com,DIRECT
- DOMAIN-SUFFIX,bamilo.com,DIRECT
- DOMAIN-SUFFIX,alibaba.ir,DIRECT
- DOMAIN-SUFFIX,ban.ir,DIRECT
- DOMAIN-KEYWORD,telegram,Auto Select
- DOMAIN-SUFFIX,t.me,Auto Select
- DOMAIN-SUFFIX,telegram.org,Auto Select
- DOMAIN-SUFFIX,google.com,Auto Select
- DOMAIN-SUFFIX,youtube.com,Auto Select
- DOMAIN-SUFFIX,github.com,Auto Select
- DOMAIN-SUFFIX,instagram.com,Auto Select
- DOMAIN-SUFFIX,twitter.com,Auto Select
- DOMAIN-SUFFIX,whatsapp.com,Auto Select
- GEOIP,IR,DIRECT
- MATCH,Proxy Select
ntp:
  enable: true
  server: time.cloudflare.com
  port: 123
  interval: 30
