mixed-port: 7890
ipv6: false
allow-lan: true
mode: rule
log-level: warning
unified-delay: false
tcp-concurrent: true
geo-auto-update: true
geo-update-interval: 168
external-controller: 127.0.0.1:9090
external-controller-cors:
  allow-origins:
  - '*'
  allow-private-network: true
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  respect-rules: true
  use-system-hosts: false
  listen: 0.0.0.0:1053
  ipv6: false
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  proxy-server-nameserver:
  - 8.8.8.8
  direct-nameserver:
  - 8.8.8.8
  direct-nameserver-follow-policy: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.localhost'
  - '*.ir'
  - '*.test'
  - '*.localdomain'
  - '*.home'
  - '*.internal'
tun:
  enable: true
  stack: gvisor
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
proxies:
- name: 'ARISTA #1'
  type: vmess
  server: mig-sin.darkube.ir
  port: 443
  uuid: 254721a9-5739-4baf-b35d-9bc950e346db
  alterId: 0
  cipher: auto
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: mig-sin.darkube.ir
  client-fingerprint: ''
  ws-opts:
    path: /api/direct
    headers:
      Host: mig-sin.darkube.ir
- name: 'ARISTA #2'
  type: vmess
  server: snapp.ir
  port: 8080
  uuid: 67fe0164-9146-47c7-8247-27ddd3eb8f00
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: rxs.bravo-six.ir
  client-fingerprint: ''
  ws-opts:
    path: /
    headers:
      Host: rxs.bravo-six.ir
- name: 'ARISTA #3'
  type: vmess
  server: 10.a400.top
  port: 44742
  uuid: 691ebfe7-756a-4b7d-836a-f292ef3b2146
  alterId: 0
  cipher: auto
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 10.a400.top
  client-fingerprint: ''
  ws-opts:
    path: /
    headers:
      Host: 10.a400.top
- name: 'ARISTA #4'
  type: vmess
  server: 165.154.195.38
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 165.154.195.38
  client-fingerprint: ''
- name: 'ARISTA #5'
  type: vmess
  server: 188.121.108.90
  port: 46742
  uuid: 221ed633-838f-4110-bf41-86936c1bc8fc
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 188.121.108.90
  client-fingerprint: ''
- name: 'ARISTA #6'
  type: vmess
  server: mig-sin.darkube.ir
  port: 443
  uuid: 254721a9-5739-4baf-b35d-9bc950e346db
  alterId: 0
  cipher: auto
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: mig-sin.darkube.ir
  client-fingerprint: ''
  ws-opts:
    path: /api/direct
    headers:
      Host: mig-sin.darkube.ir
- name: 'ARISTA #7'
  type: vmess
  server: 35.212.177.67
  port: 40029
  uuid: e8ab37c7-2b1d-4776-c062-2cac8fc066e1
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 35.212.177.67
  client-fingerprint: ''
- name: 'ARISTA #8'
  type: vmess
  server: 35.212.177.67
  port: 40029
  uuid: e8ab37c7-2b1d-4776-c062-2cac8fc066e1
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 35.212.177.67
  client-fingerprint: chrome
- name: 'ARISTA #9'
  type: vmess
  server: 67.220.72.237
  port: 22324
  uuid: 04621bae-ab36-11ec-b909-0242ac120002
  alterId: 1
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 67.220.72.237
  client-fingerprint: ''
- name: 'ARISTA #10'
  type: vmess
  server: 185.11.89.38
  port: 12809
  uuid: aeddbbbd-ad95-49e8-ee31-7cacc7ede117
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 185.11.89.38
  client-fingerprint: ''
- name: 'ARISTA #11'
  type: vmess
  server: 185.222.210.50
  port: 80
  uuid: 0873f7f8-7f58-416b-84a8-ded399d521b2
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 185.222.210.50
  client-fingerprint: ''
- name: 'ARISTA #12'
  type: vmess
  server: snapp.ir
  port: 8880
  uuid: 6fda9f31-0095-4d7f-807b-f48a39ec3768
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: dl600tobi.sudoserver.ir
  client-fingerprint: ''
  ws-opts:
    path: /
    headers:
      Host: dl600tobi.sudoserver.ir
- name: 'ARISTA #13'
  type: vmess
  server: snapp.ir
  port: 80
  uuid: 89333944-84d3-46e5-9592-e4c5bfaad81f
  alterId: 0
  cipher: auto
  network: httpupgrade
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: starlinck.parszone2.ir
  client-fingerprint: ''
- name: 'ARISTA #14'
  type: vmess
  server: v11.mailiran.net
  port: 11999
  uuid: 8257b31e-0805-4f28-9209-251b72b9a593
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: v11.mailiran.net
  client-fingerprint: ''
  ws-opts:
    path: /
    headers:
      Host: v11.mailiran.net
- name: 'ARISTA #15'
  type: vmess
  server: client.afraserverc3.top
  port: 4166
  uuid: 3c048cdd-a10c-47df-a2b7-3ed149c6e0e0
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: client.afraserverc3.top
  client-fingerprint: ''
- name: 'ARISTA #16'
  type: vmess
  server: dn.torontomovie.com
  port: 8080
  uuid: 02dcced8-c899-4269-bcd8-c902f01b4394
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: dn.torontomovie.com
  client-fingerprint: ''
- name: 'ARISTA #17'
  type: vmess
  server: dn.torontomovie.com
  port: 8080
  uuid: aad1acfb-d213-4384-b603-b3e0c77f29a2
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: dn.torontomovie.com
  client-fingerprint: ''
- name: 'ARISTA #18'
  type: vmess
  server: mig-sin.darkube.ir
  port: 443
  uuid: 254721a9-5739-4baf-b35d-9bc950e346db
  alterId: 0
  cipher: auto
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: mig-sin.darkube.ir
  client-fingerprint: chrome
  ws-opts:
    path: /api/direct
    headers:
      Host: mig-sin.darkube.ir
- name: 'ARISTA #19'
  type: vmess
  server: mig-sin.darkube.ir
  port: 443
  uuid: 254721a9-5739-4baf-b35d-9bc950e346db
  alterId: 0
  cipher: auto
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: mig-sin.darkube.ir
  client-fingerprint: ''
  ws-opts:
    path: /api/direct
    headers:
      Host: mig-sin.darkube.ir
- name: 'ARISTA #20'
  type: vmess
  server: 185.236.38.44
  port: 19946
  uuid: c9e42537-8652-4a4c-85d3-0d36abf38f88
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 185.236.38.44
  client-fingerprint: ''
- name: 'ARISTA #21'
  type: vmess
  server: i-love-iran.amlakayuni.ir
  port: 2053
  uuid: a0b58d55-b29b-7c0e-d774-3fe04fc375d8
  alterId: 0
  cipher: auto
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: i-love-iran.amlakayuni.ir
  client-fingerprint: randomized
  ws-opts:
    path: ?ed=2053
    headers:
      Host: i-love-iran.amlakayuni.ir
- name: 'ARISTA #22'
  type: vmess
  server: mig-sin.darkube.ir
  port: 443
  uuid: 254721a9-5739-4baf-b35d-9bc950e346db
  alterId: 0
  cipher: auto
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: mig-sin.darkube.ir
  client-fingerprint: ''
  ws-opts:
    path: /api/direct
    headers:
      Host: mig-sin.darkube.ir
proxy-groups:
- name: Proxy Select
  type: select
  proxies:
  - Auto Select
  - 'ARISTA #1'
  - 'ARISTA #2'
  - 'ARISTA #3'
  - 'ARISTA #4'
  - 'ARISTA #5'
  - 'ARISTA #6'
  - 'ARISTA #7'
  - 'ARISTA #8'
  - 'ARISTA #9'
  - 'ARISTA #10'
  - 'ARISTA #11'
  - 'ARISTA #12'
  - 'ARISTA #13'
  - 'ARISTA #14'
  - 'ARISTA #15'
  - 'ARISTA #16'
  - 'ARISTA #17'
  - 'ARISTA #18'
  - 'ARISTA #19'
  - 'ARISTA #20'
  - 'ARISTA #21'
  - 'ARISTA #22'
  - DIRECT
- name: Auto Select
  type: url-test
  proxies:
  - 'ARISTA #1'
  - 'ARISTA #2'
  - 'ARISTA #3'
  - 'ARISTA #4'
  - 'ARISTA #5'
  - 'ARISTA #6'
  - 'ARISTA #7'
  - 'ARISTA #8'
  - 'ARISTA #9'
  - 'ARISTA #10'
  - 'ARISTA #11'
  - 'ARISTA #12'
  - 'ARISTA #13'
  - 'ARISTA #14'
  - 'ARISTA #15'
  - 'ARISTA #16'
  - 'ARISTA #17'
  - 'ARISTA #18'
  - 'ARISTA #19'
  - 'ARISTA #20'
  - 'ARISTA #21'
  - 'ARISTA #22'
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 150
  lazy: true
rules:
- DOMAIN-SUFFIX,net2025.afsharidempire.uk,DIRECT
- DOMAIN,cp.cloudflare.com,Auto Select
- DOMAIN-SUFFIX,cdn.ir,DIRECT
- DOMAIN-SUFFIX,aparat.com,DIRECT
- DOMAIN-SUFFIX,digikala.com,DIRECT
- DOMAIN-SUFFIX,divar.ir,DIRECT
- DOMAIN-SUFFIX,snapp.ir,DIRECT
- DOMAIN-SUFFIX,torob.com,DIRECT
- DOMAIN-SUFFIX,bamilo.com,DIRECT
- DOMAIN-SUFFIX,alibaba.ir,DIRECT
- DOMAIN-SUFFIX,ban.ir,DIRECT
- DOMAIN-KEYWORD,telegram,Auto Select
- DOMAIN-SUFFIX,t.me,Auto Select
- DOMAIN-SUFFIX,telegram.org,Auto Select
- DOMAIN-SUFFIX,google.com,Auto Select
- DOMAIN-SUFFIX,youtube.com,Auto Select
- DOMAIN-SUFFIX,github.com,Auto Select
- DOMAIN-SUFFIX,instagram.com,Auto Select
- DOMAIN-SUFFIX,twitter.com,Auto Select
- DOMAIN-SUFFIX,whatsapp.com,Auto Select
- GEOIP,IR,DIRECT
- MATCH,Proxy Select
ntp:
  enable: true
  server: time.cloudflare.com
  port: 123
  interval: 30
