mixed-port: 7890
ipv6: false
allow-lan: true
mode: rule
log-level: warning
unified-delay: false
tcp-concurrent: true
geo-auto-update: true
geo-update-interval: 168
external-controller: 127.0.0.1:9090
external-controller-cors:
  allow-origins:
  - '*'
  allow-private-network: true
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  respect-rules: true
  use-system-hosts: false
  listen: 0.0.0.0:1053
  ipv6: false
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  proxy-server-nameserver:
  - 8.8.8.8
  direct-nameserver:
  - 8.8.8.8
  direct-nameserver-follow-policy: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.localhost'
  - '*.ir'
  - '*.test'
  - '*.localdomain'
  - '*.home'
  - '*.internal'
tun:
  enable: true
  stack: gvisor
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
proxies:
- name: 'ARISTA #1'
  type: vmess
  server: 185.11.89.38
  port: 12809
  uuid: aeddbbbd-ad95-49e8-ee31-7cacc7ede117
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 185.11.89.38
  client-fingerprint: ''
- name: 'ARISTA #2'
  type: vmess
  server: 82.198.246.37
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 82.198.246.37
  client-fingerprint: chrome
- name: 'ARISTA #3'
  type: vmess
  server: 165.154.195.38
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 165.154.195.38
  client-fingerprint: ''
- name: 'ARISTA #4'
  type: vmess
  server: 185.11.89.38
  port: 12809
  uuid: aeddbbbd-ad95-49e8-ee31-7cacc7ede117
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 185.11.89.38
  client-fingerprint: ''
- name: 'ARISTA #5'
  type: vmess
  server: 94.101.178.69
  port: 45384
  uuid: 625dd187-60c2-40d5-899d-0af7c5c25a84
  alterId: 0
  cipher: auto
  network: grpc
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 94.101.178.69
  client-fingerprint: ''
  grpc-opts:
    grpc-service-name: ''
- name: 'ARISTA #6'
  type: vmess
  server: cp.paeadiy.com
  port: 1402
  uuid: 7f3dbc61-f140-37c4-9fbd-ec649ea2d792
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: cp.paeadiy.com
  client-fingerprint: ios
- name: 'ARISTA #7'
  type: vmess
  server: cp.paeadiy.com
  port: 53100
  uuid: 7f3dbc61-f140-37c4-9fbd-ec649ea2d792
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: cp.paeadiy.com
  client-fingerprint: safari
- name: 'ARISTA #8'
  type: vmess
  server: v30.hdacd.com
  port: 30830
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: v30.hdacd.com
  client-fingerprint: ios
- name: 'ARISTA #9'
  type: vmess
  server: 185.236.38.44
  port: 19946
  uuid: c9e42537-8652-4a4c-85d3-0d36abf38f88
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 185.236.38.44
  client-fingerprint: ''
- name: 'ARISTA #10'
  type: vmess
  server: 94.101.178.69
  port: 45384
  uuid: 625dd187-60c2-40d5-899d-0af7c5c25a84
  alterId: 0
  cipher: auto
  network: grpc
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 94.101.178.69
  client-fingerprint: ''
  grpc-opts:
    grpc-service-name: ''
- name: 'ARISTA #11'
  type: vmess
  server: cdn.ip-static.com
  port: 80
  uuid: a9311ff2-14bf-4ba6-8601-42028a7e3a84
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: FIN003.midasnet.work
  client-fingerprint: ''
  ws-opts:
    path: /
    headers:
      Host: FIN003.midasnet.work
- name: 'ARISTA #12'
  type: vmess
  server: 94.101.178.69
  port: 45384
  uuid: 625dd187-60c2-40d5-899d-0af7c5c25a84
  alterId: 0
  cipher: auto
  network: grpc
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 94.101.178.69
  client-fingerprint: ''
  grpc-opts:
    grpc-service-name: ''
- name: 'ARISTA #13'
  type: vmess
  server: b51d64cb-c5d6-4791-8ecf-0a6d8d71c717.wtf
  port: 20780
  uuid: a44eef00-7578-427a-884a-79daf9dc8e50
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: b51d64cb-c5d6-4791-8ecf-0a6d8d71c717.wtf
  client-fingerprint: ''
- name: 'ARISTA #14'
  type: vmess
  server: cdn.ip-static.com
  port: 80
  uuid: 2d15c43f-eb41-459d-b520-02f24d371082
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: SWE001.midasnet.work
  client-fingerprint: ''
  ws-opts:
    path: /
    headers:
      Host: SWE001.midasnet.work
- name: 'ARISTA #15'
  type: vmess
  server: cdn.ip-static.com
  port: 80
  uuid: 04220b25-830e-46ea-8518-b0f26be9b668
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: deu005.midasnet.work
  client-fingerprint: ''
  ws-opts:
    path: /
    headers:
      Host: deu005.midasnet.work
- name: 'ARISTA #16'
  type: vmess
  server: dl.atlanticteamchannel2.blog
  port: 80
  uuid: 90ec693e-7c00-4a15-974a-6bcf9beb89ac
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: dl.atlanticteamchannel2.blog
  client-fingerprint: ''
- name: 'ARISTA #17'
  type: vmess
  server: 35.212.177.67
  port: 40029
  uuid: e8ab37c7-2b1d-4776-c062-2cac8fc066e1
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 35.212.177.67
  client-fingerprint: ''
- name: 'ARISTA #18'
  type: vmess
  server: 35.212.177.67
  port: 40029
  uuid: e8ab37c7-2b1d-4776-c062-2cac8fc066e1
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 35.212.177.67
  client-fingerprint: chrome
- name: 'ARISTA #19'
  type: vmess
  server: 67.220.72.237
  port: 22324
  uuid: 04621bae-ab36-11ec-b909-0242ac120002
  alterId: 1
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 67.220.72.237
  client-fingerprint: ''
- name: 'ARISTA #20'
  type: vmess
  server: snapp.ir
  port: 80
  uuid: 07f522fc-325c-4f8e-a9ce-f55a7df67e60
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: ar1.techroads.ir
  client-fingerprint: ''
  ws-opts:
    path: /
    headers:
      Host: ar1.techroads.ir
- name: 'ARISTA #21'
  type: vmess
  server: snapp.ir
  port: 8880
  uuid: ad09cb55-04cb-4b08-9915-50e37e8c9b5b
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: dl600tobi.sudoserver.ir
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: dl600tobi.sudoserver.ir
- name: 'ARISTA #22'
  type: vmess
  server: b51d64cb-c5d6-4791-8ecf-0a6d8d71c717.wtf
  port: 20782
  uuid: a480e28a-8227-4701-93f6-f3661fd323c7
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: b51d64cb-c5d6-4791-8ecf-0a6d8d71c717.wtf
  client-fingerprint: ''
- name: 'ARISTA #23'
  type: vmess
  server: cdn.ip-static.com
  port: 80
  uuid: 0a1b9e44-2794-46bd-8bc7-5615cc21edcd
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: FIN001.midasnet.work
  client-fingerprint: ''
  ws-opts:
    path: /
    headers:
      Host: FIN001.midasnet.work
- name: 'ARISTA #24'
  type: vmess
  server: fars.sanprime.ir
  port: 47395
  uuid: 6e66b82f-2f82-414a-b7c9-456a3330d81b
  alterId: 0
  cipher: auto
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: web.sanprime.ir
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
- name: 'ARISTA #25'
  type: vmess
  server: 185.11.89.38
  port: 12809
  uuid: aeddbbbd-ad95-49e8-ee31-7cacc7ede117
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 185.11.89.38
  client-fingerprint: ''
- name: 'ARISTA #26'
  type: vmess
  server: 188.121.108.90
  port: 46742
  uuid: 221ed633-838f-4110-bf41-86936c1bc8fc
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 188.121.108.90
  client-fingerprint: ''
proxy-groups:
- name: Proxy Select
  type: select
  proxies:
  - Auto Select
  - 'ARISTA #1'
  - 'ARISTA #2'
  - 'ARISTA #3'
  - 'ARISTA #4'
  - 'ARISTA #5'
  - 'ARISTA #6'
  - 'ARISTA #7'
  - 'ARISTA #8'
  - 'ARISTA #9'
  - 'ARISTA #10'
  - 'ARISTA #11'
  - 'ARISTA #12'
  - 'ARISTA #13'
  - 'ARISTA #14'
  - 'ARISTA #15'
  - 'ARISTA #16'
  - 'ARISTA #17'
  - 'ARISTA #18'
  - 'ARISTA #19'
  - 'ARISTA #20'
  - 'ARISTA #21'
  - 'ARISTA #22'
  - 'ARISTA #23'
  - 'ARISTA #24'
  - 'ARISTA #25'
  - 'ARISTA #26'
  - DIRECT
- name: Auto Select
  type: url-test
  proxies:
  - 'ARISTA #1'
  - 'ARISTA #2'
  - 'ARISTA #3'
  - 'ARISTA #4'
  - 'ARISTA #5'
  - 'ARISTA #6'
  - 'ARISTA #7'
  - 'ARISTA #8'
  - 'ARISTA #9'
  - 'ARISTA #10'
  - 'ARISTA #11'
  - 'ARISTA #12'
  - 'ARISTA #13'
  - 'ARISTA #14'
  - 'ARISTA #15'
  - 'ARISTA #16'
  - 'ARISTA #17'
  - 'ARISTA #18'
  - 'ARISTA #19'
  - 'ARISTA #20'
  - 'ARISTA #21'
  - 'ARISTA #22'
  - 'ARISTA #23'
  - 'ARISTA #24'
  - 'ARISTA #25'
  - 'ARISTA #26'
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 150
  lazy: true
rules:
- DOMAIN-SUFFIX,net2025.afsharidempire.uk,DIRECT
- DOMAIN,cp.cloudflare.com,Auto Select
- DOMAIN-SUFFIX,cdn.ir,DIRECT
- DOMAIN-SUFFIX,aparat.com,DIRECT
- DOMAIN-SUFFIX,digikala.com,DIRECT
- DOMAIN-SUFFIX,divar.ir,DIRECT
- DOMAIN-SUFFIX,snapp.ir,DIRECT
- DOMAIN-SUFFIX,torob.com,DIRECT
- DOMAIN-SUFFIX,bamilo.com,DIRECT
- DOMAIN-SUFFIX,alibaba.ir,DIRECT
- DOMAIN-SUFFIX,ban.ir,DIRECT
- DOMAIN-KEYWORD,telegram,Auto Select
- DOMAIN-SUFFIX,t.me,Auto Select
- DOMAIN-SUFFIX,telegram.org,Auto Select
- DOMAIN-SUFFIX,google.com,Auto Select
- DOMAIN-SUFFIX,youtube.com,Auto Select
- DOMAIN-SUFFIX,github.com,Auto Select
- DOMAIN-SUFFIX,instagram.com,Auto Select
- DOMAIN-SUFFIX,twitter.com,Auto Select
- DOMAIN-SUFFIX,whatsapp.com,Auto Select
- GEOIP,IR,DIRECT
- MATCH,Proxy Select
ntp:
  enable: true
  server: time.cloudflare.com
  port: 123
  interval: 30
