mixed-port: 7890
ipv6: false
allow-lan: true
mode: rule
log-level: warning
unified-delay: false
tcp-concurrent: true
geo-auto-update: true
geo-update-interval: 168
external-controller: 127.0.0.1:9090
external-controller-cors:
  allow-origins:
  - '*'
  allow-private-network: true
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  respect-rules: true
  use-system-hosts: false
  listen: 0.0.0.0:1053
  ipv6: false
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  proxy-server-nameserver:
  - 8.8.8.8
  direct-nameserver:
  - 8.8.8.8
  direct-nameserver-follow-policy: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.localhost'
  - '*.ir'
  - '*.test'
  - '*.localdomain'
  - '*.home'
  - '*.internal'
tun:
  enable: true
  stack: gvisor
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
proxies:
- name: 'ARISTA #1'
  type: vmess
  server: 5.202.8.228
  port: 443
  uuid: f4f997de-e68b-443b-9564-457e6af80e1c
  alterId: 0
  cipher: auto
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: java.basic-tutorial.ir
  client-fingerprint: chrome
  alpn:
  - http/1.1
  ws-opts:
    path: /28hzxvljFN5Qx9
    headers:
      Host: java.basic-tutorial.ir
- name: 'ARISTA #2'
  type: vmess
  server: 104.17.78.159
  port: 443
  uuid: 9880cba6-7260-4eab-a446-d9f4b02b28bd
  alterId: 0
  cipher: auto
  network: httpupgrade
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: worker.shayan.cyou
  client-fingerprint: chrome
  alpn:
  - http/1.1
- name: 'ARISTA #3'
  type: vmess
  server: www.darkroom.lol
  port: 8080
  uuid: 22826b44-5c1a-4b4b-dbaa-83a2e8bd95f0
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.darkroom.lol
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: www.darkroom.lol
- name: 'ARISTA #4'
  type: vmess
  server: cn01.365cloud8754.com
  port: 6001
  uuid: db75bc92-4e32-48dd-b792-d7a8b707626c
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: cn01.365cloud8754.com
  client-fingerprint: chrome
- name: 'ARISTA #5'
  type: vmess
  server: t.cnmjcn.cyou
  port: 16616
  uuid: d95d95c5-8222-43a8-a7f9-ab2b1be317a6
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 8f0265a9fe8497203bee1c343489f105.mobgslb.tbcache.com
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: 8f0265a9fe8497203bee1c343489f105.mobgslb.tbcache.com
- name: 'ARISTA #6'
  type: vmess
  server: 13.231.142.241
  port: 8686
  uuid: 1a17b19d-4896-4531-af79-6e91d8ef8228
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: baidu.com
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: end-gfw.com
- name: 'ARISTA #7'
  type: vmess
  server: 47.245.15.239
  port: 443
  uuid: a5047d95-24b8-451a-93e3-f2a387b93d5a
  alterId: 0
  cipher: null
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: n1753598446.wpg27.xyz
  client-fingerprint: null
  ws-opts:
    path: /
    headers:
      Host: n1753598446.wpg27.xyz
- name: 'ARISTA #8'
  type: vmess
  server: 45.85.119.45
  port: 2083
  uuid: fbd1c32e-de4b-443e-f521-0a20b9b54f5d
  alterId: 0
  cipher: auto
  network: grpc
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: hxf.hoxbkf.xyz
  client-fingerprint: chrome
  grpc-opts:
    grpc-service-name: hxf.hoxbkf.xyz
- name: 'ARISTA #9'
  type: vmess
  server: m.cnmjin.net
  port: 16617
  uuid: 42355be2-af61-4b3b-866c-d3c5ea8748c5
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: febce1d29a8a4c68e016e0bec83fa245.mobgslb.tbcache.com
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: febce1d29a8a4c68e016e0bec83fa245.mobgslb.tbcache.com
- name: 'ARISTA #10'
  type: vmess
  server: t.cnmjcn.cyou
  port: 16618
  uuid: 42355be2-af61-4b3b-866c-d3c5ea8748c5
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: febce1d29a8a4c68e016e0bec83fa245.mobgslb.tbcache.com
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: febce1d29a8a4c68e016e0bec83fa245.mobgslb.tbcache.com
- name: 'ARISTA #11'
  type: vmess
  server: v2ray.codefyinc.com
  port: 443
  uuid: 2c981164-9b93-4bca-94ff-b78d3f8498d7
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: v2ray.codefyinc.com
  client-fingerprint: ''
  ws-opts:
    path: /vmessws
    headers:
      Host: v2ray.codefyinc.com
- name: 'ARISTA #12'
  type: vmess
  server: 45.12.132.183
  port: 80
  uuid: 703f722a-4bdf-4e9d-9afd-a681fdf87c74
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 45.12.132.183
  client-fingerprint: ''
  ws-opts:
    path: /vmess/
    headers:
      Host: 45.12.132.183
- name: 'ARISTA #13'
  type: vmess
  server: 165.140.216.141
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 165.140.216.141
  client-fingerprint: ''
- name: 'ARISTA #14'
  type: vmess
  server: 65.21.145.122
  port: 53442
  uuid: cd13ae55-feca-457c-988e-8dba56fe006f
  alterId: 0
  cipher: auto
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.microsoft.com
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
proxy-groups:
- name: Proxy Select
  type: select
  proxies:
  - Auto Select
  - 'ARISTA #1'
  - 'ARISTA #2'
  - 'ARISTA #3'
  - 'ARISTA #4'
  - 'ARISTA #5'
  - 'ARISTA #6'
  - 'ARISTA #7'
  - 'ARISTA #8'
  - 'ARISTA #9'
  - 'ARISTA #10'
  - 'ARISTA #11'
  - 'ARISTA #12'
  - 'ARISTA #13'
  - 'ARISTA #14'
  - DIRECT
- name: Auto Select
  type: url-test
  proxies:
  - 'ARISTA #1'
  - 'ARISTA #2'
  - 'ARISTA #3'
  - 'ARISTA #4'
  - 'ARISTA #5'
  - 'ARISTA #6'
  - 'ARISTA #7'
  - 'ARISTA #8'
  - 'ARISTA #9'
  - 'ARISTA #10'
  - 'ARISTA #11'
  - 'ARISTA #12'
  - 'ARISTA #13'
  - 'ARISTA #14'
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 150
  lazy: true
rules:
- DOMAIN-SUFFIX,net2025.afsharidempire.uk,DIRECT
- DOMAIN,cp.cloudflare.com,Auto Select
- DOMAIN-SUFFIX,cdn.ir,DIRECT
- DOMAIN-SUFFIX,aparat.com,DIRECT
- DOMAIN-SUFFIX,digikala.com,DIRECT
- DOMAIN-SUFFIX,divar.ir,DIRECT
- DOMAIN-SUFFIX,snapp.ir,DIRECT
- DOMAIN-SUFFIX,torob.com,DIRECT
- DOMAIN-SUFFIX,bamilo.com,DIRECT
- DOMAIN-SUFFIX,alibaba.ir,DIRECT
- DOMAIN-SUFFIX,ban.ir,DIRECT
- DOMAIN-KEYWORD,telegram,Auto Select
- DOMAIN-SUFFIX,t.me,Auto Select
- DOMAIN-SUFFIX,telegram.org,Auto Select
- DOMAIN-SUFFIX,google.com,Auto Select
- DOMAIN-SUFFIX,youtube.com,Auto Select
- DOMAIN-SUFFIX,github.com,Auto Select
- DOMAIN-SUFFIX,instagram.com,Auto Select
- DOMAIN-SUFFIX,twitter.com,Auto Select
- DOMAIN-SUFFIX,whatsapp.com,Auto Select
- GEOIP,IR,DIRECT
- MATCH,Proxy Select
ntp:
  enable: true
  server: time.cloudflare.com
  port: 123
  interval: 30
